FROM python:3.11-slim

# Set the maintainer label to link the container to the github repository
LABEL org.opencontainers.image.source https://github.com/darioblanco/fastapi-example

# Set the working directory to /app
WORKDIR /app

# Install pip and poetry
RUN pip install --upgrade pip \
    && pip install --no-cache-dir uvicorn poetry

# Copy only requirements to cache them in docker layer
COPY poetry.lock pyproject.toml ./

# Project initialization:
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# Copy all files
COPY . .

# Define the entrypoint script
COPY container/entrypoint.sh /entrypoint.sh

# Ensure the entrypoint script is executable
RUN chmod +x /entrypoint.sh

EXPOSE 8080

# Define the script to run at container startup
ENTRYPOINT ["/entrypoint.sh"]
