version: "3.8"

networks:
  default:
    name: fastapi-example
    driver: bridge

volumes:
  db_data:

services:
  app:
    image: fastapi-example:latest
    hostname: fastapi-example
    container_name: fastapi-example-app
    build:
      context: ../
      dockerfile: container/Containerfile
    environment:
      ALEMBIC_URI: postgresql://sampleapi:secret@postgres:5432/sampleapi
      DATABASE_URI: postgresql+asyncpg://sampleapi:secret@postgres:5432/sampleapi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:80

  db:
    image: postgres:15-alpine
    hostname: postgres
    container_name: fastapi-example-db
    environment:
      POSTGRES_DB: sampleapi
      POSTGRES_USER: sampleapi
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "sampleapi", "-U", "sampleapi"]
      timeout: 45s
      interval: 5s
      retries: 10

  db-test:
    image: postgres:15-alpine
    hostname: postgres
    container_name: fastapi-example-db-test
    environment:
      POSTGRES_DB: test_sampleapi
      POSTGRES_USER: sampleapi
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    healthcheck:
      test:
        ["CMD", "pg_isready", "-q", "-d", "test_sampleapi", "-U", "sampleapi"]
      timeout: 45s
      interval: 5s
      retries: 10
