repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            build,
            chore,
            ci,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
          ]
  - repo: local
    hooks:
      - id: pre-commit-hook
        name: auto format code files
        language: script
        entry: ./pre-commit-hook.sh
