apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastapi-example
resources:
  - ../base
  - docker-secret.enc.yaml
  - secret.enc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
configMapGenerator:
  - name: fastapi-example # it will replace the configmap that it founds with this name and add a hash
    behavior: merge
    literals:
      - ENV=prod
images:
  - name: ghcr.io/darioblanco/fastapi-example # {"$imagepolicy": "flux-system:fastapi-example:name"}
    newTag: main-46dae481-1689885151 # {"$imagepolicy": "flux-system:fastapi-example:tag"}
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: fastapi-example
