apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-example
spec:
  selector:
    matchLabels:
      env: dev
  template:
    spec:
      containers:
        - name: fastapi-example
          resources:
            limits:
              cpu: "0.1"
              memory: "128Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
      imagePullSecrets:
        - name: fastapi-example-docker
