apiVersion: v1
kind: Secret
metadata:
  name: fastapi-example
type: Opaque
stringData:
  DATABASE_URI: ENC[AES256_GCM,data:4zYHsgwzrzVQ1AtD/s+G3E1tBXjq4M6qFKeCeza/eNB21ADVNnmefInkS3CLfrDEmIWlkuTMgNEcHVfQJAxthmfxgrZTsfo2,iv:CVCioirF4t2ZFyornohl+fndGvUzLSx7j3v2mlUnN/w=,tag:unCV5VXDvEbA8T7OhWPqpw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:wnLAktdba+BtYgMHisYehE4=,iv:dERXxQ0PXtJTIfvmh0YsxZEwr9WSo/ID4rphlJl+BpQ=,tag:01xJfr7eaai8Pg5Gdm1ekQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g2wjea9r33l6w0kr6g49yh2tgz3mx6l6dt9a8umaf6fzdkgfsemqmrzxxg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSisrK2E0ZVhrRzBUYlVI
        UmtaUDBOc1h6NzNGWHpQUkVKc2RjR05VQmd3CnhnV2dWbEtCMHRieGNOZXVzYlEz
        RFdFK1lHaGY1bVVSNFJsRmtGMmxDb1EKLS0tIFI5TWYvamtxMVRwNW5DZ0pEaGVB
        cm1BNGcvbVZaZitCK1BjYXJPRE10eUEKBsxO84BnLh/DtTqdLQoVMx3e/qlZN3Z8
        TRKa6yUmM1WamKV88qYOBlxVRFUGYLGkohQGCSjwAzLCwckFU8KF6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-18T09:25:27Z"
  mac: ENC[AES256_GCM,data:8RDapMD8EkLBQaY3JCvJK6IEguWABaN/TuXY//fQt+Qkty915D5FZO96P50At/ooxf1Mm57/1wznRsEL7fZfiCR6YBBAKel3jxNgLl81iZGgmjqEniSsK3MoDNEPaJ/FNf1OqK3p+QQbm8QsT8fAHQf3Per2FQjfx9exImPPgVQ=,iv:ULTkrCR3NKWOd7lbI/gr9zgK0QogoUyBVR6JIPA7wUQ=,tag:hEUZPtMzSGWrx1DioKBV1g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
