"""New space agencies model.

Revision ID: 0a9e36da2fc7
Revises: 716fb76750ec
Create Date: 2023-07-09 01:25:47.969995

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a9e36da2fc7"
down_revision = "716fb76750ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space_agencies",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=350), nullable=True),
        sa.Column(
            "website", sqlalchemy_utils.types.url.URLType(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("space_agencies")
    # ### end Alembic commands ###
