apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastapi-example
resources:
  - ../base
  - postgres-deployment.yaml
  - postgres-service.yaml
  - secret.enc.yaml
configMapGenerator:
  - name: fastapi-example # it will replace the configmap that it founds with this name and add a hash
    behavior: merge
    literals:
      - ENV=prod
images:
  - name: ghcr.io/darioblanco/fastapi-example
    newTag: latest
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
