name: container
on:
  deployment:
  workflow_dispatch:
    inputs:
      version:
        description: Container version to push (by default pushes the latest change)
        default: ""
        required: false
jobs:
  build:
    uses: darioblanco/.github/.github/workflows/container.yaml@v1
    with:
      name: fastapi-example
      contextPath: .
      filePath: container/Containerfile
      version: ${{ github.event.inputs.version || '' }}
    secrets:
      registryPassword: ${{ secrets.REPO_ACCESS_TOKEN }}
  update-deployment:
    if: github.event_name == 'deployment'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - if: success()
        name: Successful ${{ github.event.deployment.payload.name }} deployment
        uses: chrnorm/deployment-status@v2
        with:
          deployment-id: ${{ github.event.deployment.id }}
          environment-url: ${{ github.event.deployment.payload.url }}
          environment: ${{ github.event.deployment.payload.env }}
          state: "success"
          token: ${{ github.token }}
      - if: failure()
        name: Failed ${{ github.event.deployment.payload.name }} deployment
        uses: chrnorm/deployment-status@v2
        with:
          deployment-id: ${{ github.event.deployment.id }}
          environment-url: ${{ github.event.deployment.payload.url }}
          environment: ${{ github.event.deployment.payload.env }}
          state: "failure"
          token: ${{ github.token }}
