name: App Python
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - alembic.ini
      - Containerfile
      - Makefile
      - poetry.lock
      - pyproject.toml
      - .github/workflows/python.yaml
  pull_request:
    paths:
      - "**.py"
      - alembic.ini
      - Containerfile
      - Makefile
      - poetry.lock
      - pyproject.toml
      - .github/workflows/python.yaml
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DATABASE_TEST_URI: sqlite+aiosqlite:///./test.db
      ENV: test
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install requirements
        run: make install
      - name: Validate code style
        run: make lint
      - name: Test code
        run: make test
  draft:
    if: github.ref == 'refs/heads/main'
    needs:
      - verify
    uses: darioblanco/.github/.github/workflows/release.yaml@v1
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN }}
  staging:
    if: github.ref == 'refs/heads/main'
    needs:
      - verify
    uses: darioblanco/.github/.github/workflows/deployment.yaml@v1
    with:
      author: ${{ github.event.pusher.name }}
      description: ${{ toJSON(github.event.head_commit.message) }}
      env: staging
      name: fastapi-example
      ref: ${{ github.ref }}
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN }}
  deploy_to_prod:
    if: github.ref_type == 'tag'
    needs:
      - verify
    uses: darioblanco/.github/.github/workflows/deployment.yaml@v1
    with:
      author: ${{ github.event.pusher.name }}
      description: ${{ toJSON(github.event.head_commit.message) }}
      env: prod
      name: fastapi-example
      ref: ${{ github.ref }}
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN }}
